# Generated by Django 3.0.2 on 2020-02-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Address', models.TextField()),
                ('Email', models.CharField(default='abc', max_length=120)),
                ('Mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
