# Generated by Django 2.2.8 on 2020-02-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myaccount',
            old_name='user',
            new_name='User',
        ),
    ]
