# Generated by Django 2.2.8 on 2020-02-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='ProfilePic',
            field=models.ImageField(blank=True, upload_to='profilePictures'),
        ),
    ]
