# Generated by Django 2.2.8 on 2020-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20200204_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
