# Generated by Django 2.2.8 on 2020-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_auto_20200208_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
