# Generated by Django 2.2.8 on 2020-03-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=120)),
                ('Tags', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='upload/image/prize_images')),
            ],
        ),
    ]
