# Generated by Django 2.2.8 on 2020-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='Image',
            field=models.ImageField(blank=True, upload_to='prizeImages'),
        ),
    ]
