# Generated by Django 2.2.8 on 2020-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0002_auto_20200222_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='Image',
            field=models.ImageField(upload_to='prizeImages'),
        ),
    ]
