# Generated by Django 2.2.8 on 2020-03-13 18:38

import childAccount.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField(default=childAccount.models.today_utc)),
                ('Gender', models.CharField(blank=True, choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=5, null=True)),
                ('School', models.CharField(blank=True, max_length=255)),
                ('SchoolGrade', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], default='Kindergarten', max_length=15)),
                ('Aboutme', models.TextField(blank=True)),
                ('FavoriteThing', models.TextField(blank=True)),
                ('Dream', models.TextField(blank=True)),
                ('SuperPowers', models.TextField(blank=True)),
                ('Support', models.CharField(blank=True, max_length=255)),
                ('Photo', models.ImageField(blank=True, upload_to='upload/image/profile_picture_child')),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Name', 'DOB')},
            },
        ),
    ]
