# Generated by Django 2.2.8 on 2020-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childAccount', '0002_auto_20200206_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childaccount',
            name='SchoolGrade',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], default='Kindergarten', max_length=15),
        ),
    ]
