# Generated by Django 2.2.8 on 2020-02-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childAccount', '0003_auto_20200212_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childaccount',
            name='ImpactEmblem',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='childaccount',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
    ]
