# Generated by Django 2.2.8 on 2020-02-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childAccount', '0004_auto_20200216_1745'),
        ('childAccount', '0004_auto_20200216_1443'),
    ]

    operations = [
    ]
