# Generated by Django 3.0.2 on 2020-03-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childAccount', '0006_auto_20200227_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaccount',
            name='Gender',
            field=models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='childaccount',
            unique_together={('Name', 'DOB')},
        ),
    ]
