# Generated by Django 3.0.2 on 2020-02-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=50)),
                ('Video_Name', models.CharField(max_length=30)),
                ('Video', models.FileField(upload_to='projectVideo/')),
                ('Badge', models.ImageField(upload_to='projectBadge/')),
                ('Banner', models.ImageField(upload_to='projectBanner/')),
            ],
        ),
    ]
