# Generated by Django 2.2.8 on 2020-03-13 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prize', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Goal', models.TextField(default='')),
                ('Mission', models.TextField(default='')),
                ('Category', models.CharField(max_length=50)),
                ('Video_Name', models.CharField(max_length=30, null=True)),
                ('Video', models.FileField(null=True, upload_to='upload/video/project_video/')),
                ('Badge', models.ImageField(null=True, upload_to='upload/image/project_badge/')),
                ('Tags', models.TextField(default='')),
                ('Banner', models.ImageField(null=True, upload_to='upload/image/project_banner/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('goal_date', models.DateField(blank=True, null=True)),
                ('challenge_status', models.CharField(blank=True, max_length=100)),
                ('project_status', models.CharField(blank=True, max_length=100)),
                ('adventure_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityprojects.CharityProjects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('prize_given_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
        migrations.CreateModel(
            name='UnregisterInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unregister_user_emailId', models.CharField(max_length=100, null=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('prize_given_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='upload/video/invitation_video')),
                ('prize_given_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
        migrations.CreateModel(
            name='LearnNewSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newSkill', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(null=True, upload_to='upload/video/challenge_video')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
    ]
