# Generated by Django 3.0.2 on 2020-02-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprojects',
            name='Goal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='charityprojects',
            name='Mission',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='charityprojects',
            name='Tags',
            field=models.TextField(default=''),
        ),
    ]
