# Generated by Django 3.0.2 on 2020-03-09 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0002_auto_20200225_0211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('goal_date', models.DateField(blank=True, null=True)),
                ('challenge_status', models.CharField(blank=True, max_length=100)),
                ('project_status', models.CharField(blank=True, max_length=100)),
                ('adventure_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='charityprojects',
            name='Goal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='charityprojects',
            name='Mission',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='charityprojects',
            name='Tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Badge',
            field=models.ImageField(null=True, upload_to='upload/projectBadge/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Banner',
            field=models.ImageField(null=True, upload_to='upload/projectBanner/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Video',
            field=models.FileField(null=True, upload_to='upload/projectVideo/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Video_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('prize_given_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='InvitationVideo')),
                ('prize_given_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
        migrations.AddField(
            model_name='projectuser',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityprojects.CharityProjects'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LearnNewSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newSkill', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(null=True, upload_to='upload/challengeVideo')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
    ]
