# Generated by Django 3.0.2 on 2020-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0002_auto_20200219_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprojects',
            name='Badge',
            field=models.ImageField(blank=True, null=True, upload_to='projectBadge/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to='projectBanner/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='projectVideo/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Video_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
