# Generated by Django 2.2.8 on 2020-02-25 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0004_prize_projectuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
