# Generated by Django 2.2.8 on 2020-02-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0002_auto_20200225_0211'),
        ('charityprojects', '0005_delete_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='InvitationVideo')),
                ('prize_given_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
    ]
