# Generated by Django 2.2.8 on 2020-02-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0006_projectuserdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserdetails',
            name='prize_given_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize'),
        ),
        migrations.AlterField(
            model_name='projectuserdetails',
            name='pu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser'),
        ),
    ]
