# Generated by Django 3.0.2 on 2020-03-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0008_auto_20200227_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='adventure_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='challenge_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='goal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='project_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
