# Generated by Django 2.2.8 on 2020-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0009_auto_20200301_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprojects',
            name='Badge',
            field=models.ImageField(null=True, upload_to='upload/projectBadge/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Banner',
            field=models.ImageField(null=True, upload_to='upload/projectBanner/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Video',
            field=models.FileField(null=True, upload_to='upload/projectVideo/'),
        ),
        migrations.AlterField(
            model_name='charityprojects',
            name='Video_Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
