# Generated by Django 3.0.2 on 2020-03-07 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prize', '0002_auto_20200225_0211'),
        ('charityprojects', '0010_auto_20200303_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('prize_given_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.Prize')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnNewSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newSkill', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(null=True, upload_to='upload/challengeVideo')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
    ]
