# Generated by Django 2.2.8 on 2020-03-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityprojects', '0010_auto_20200303_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnNewSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newSkill', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(null=True, upload_to='upload/challengeVideo')),
                ('pu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityprojects.ProjectUser')),
            ],
        ),
    ]
