# Generated by Django 3.0.2 on 2020-02-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='', max_length=6),
        ),
    ]
